version: '3'
services:
  ipsec-vpn:
    container_name: ipsec-vpn-server
    image: hwdsl2/ipsec-vpn-server
    restart: unless-stopped
    volumes:
      - ./ikev2-vpn-data:/etc/ipsec.d
      - ./lib-modules/:/lib/modules/:ro
    environment:
      - VPN_USER=${IPSEC_USER}
      - VPN_PASSWORD=${IPSEC_PASSWORD}
      - VPN_IPSEC_PSK=${IPSEC_PSK}
      - VPN_DNS_SRV1=${IPSEC_DNS_SRV1}
      - VPN_DNS_SRV2=${IPSEC_DNS_SRV2}
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
  adguard:
    network_mode: host
    container_name: adguardhome
    image: adguard/adguardhome
    restart: unless-stopped
    ports:
      - 53:53/tcp
      - 53:53/udp
      - 67:67/udp
      # - 68:68/udp
      - 80:80/tcp
      - 443:443/tcp
      - 443:443/udp
      - 3000:3000/tcp
      - 853:853/tcp
      - 784:784/udp
      - 853:853/udp
      - 8853:8853/udp
      - 5443:5443/tcp
      - 5443:5443/udp
    volumes:
      - ./adguard/work:/opt/adguardhome/work
      - ./adguard/conf:/opt/adguardhome/conf
