version: '3'
services:
  ipsec-vpn:
    container_name: ipsec-vpn-server
    image: hwdsl2/ipsec-vpn-server
    restart: unless-stopped
    volumes:
      - ./ikev2-vpn-data:/etc/ipsec.d
      - ./lib-modules/:/lib/modules/:ro
    environment:
      - VPN_USER=${IPSEC_USER}
      - VPN_PASSWORD=${IPSEC_PASSWORD}
      - VPN_IPSEC_PSK=${IPSEC_PSK}
      - VPN_DNS_SRV1=${IPSEC_DNS_SRV1}
      - VPN_DNS_SRV2=${IPSEC_DNS_SRV2}
    ports:
      - "500:500/udp"
      - "4500:4500/udp"
    privileged: true
